title: Learning Michal's page.
author: Michal
email: michal@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
theme: jekyll-theme-time-machine

show_excerpts: true # set to false to remove excerpts on the homepage
